### ISSUE TITLE
Ecran de connexion

### ISSUE THREAD

**Issue by atillay** [tomacla/biketeam-reactjs#27]
Reproduire la page de connexion : https://www.biketeam.info/login
Permettre à l'utilisateur de s'authentifier via Strava, Facebook et Google
Stocker le token, gérer le refresh
Afficher l'utilisateur connecté dans le header (nom, prénom et avatar)

**Comment by tomacla** [comment]
### Liens d'authentification

Voici les liens pour s'authentifier (remplacer biketeam url par `staging.biketeam.info` ou `www.biketeam.info` en fonction de staging et prod) : 

- Lien pour strava : https://staging.biketeam.info/oauth2/authorization/strava?requestUri=XXX
- Lien pour google : https://staging.biketeam.info/oauth2/authorization/google?requestUri=XXX
- Lien pour facebook : https://staging.biketeam.info/oauth2/authorization/facebook?requestUri=XXX

Le paramètre requestUri doit être l'URL de redirection à savoir par exemple `http%3A%2F%2Flocalhost%3A8080%2Ftest` si tu veux être redirigé vers `http://localhost:8080/test` une fois l'authentification terminée.

### Cas de l'erreur

Si l'utilisateur n'arrive pas à se connecter ou refuse de donner les accès nécessaires, tu es redirigée vers ta page avec le paramètre  `error=AUTHENTICATION_ERROR` dans l'URL.

### Cas du succès

#### Récupérer tes tokens

En cas de succès tu es redirigé vers la page que tu as mis en requestUri avec un request param dans l'URL `sso=XXX`.

Le paramètre XXX est valable 20 secondes et te permet de récupérer tes tokens.

`POST https://staging.biketeam.info/api/auth/sso`
body en text/plain : la valeur XXX du paramètre SSO
réponse : 
```
{
    "accessToken": "AAA_TOKEN",
    "refreshToken": "RRR_TOKEN"
}
```

Le access est valable 1 jour. Le refresh est valable 30 jours. Ce ne sont pas des JWT car j'ai pas eu le temps de mettre des clés de signature etc... Je ferai ca plus tard.

Les appels API sont authentifiés avec le header X-Auth-Token qui prend la valeur du accessToken

#### Savoir qui est connecté

`GET https://staging.biketeam.info/api/auth/me`
header X-Auth-Token : AAA_TOKEN
réponse :  le user connecté

#### Rafraichir la session avec le refresh

`POST https://staging.biketeam.info/api/auth/refresh`
body en text/plain : la valeur RRR_TOKEN du refresh
réponse : des nouveaux tokens valides
